version: '3'
services:
  semezana:
    build: .
    restart: always
    depends_on:
      - db
      - nsqlookupd
      - nsqd  
    ports:
      - "8080:8080"
    environment:
      - DEBUG=false
      - PORT=8080
      - CORS_ALLOWED_ORIGINS="*"
      - SECRET_KEY="something is cooking"
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=semezana
      - DB_PASSWORD=postgres
      - NSQ_ADDRESS=nsqd:4150
      - NSQ_LOOKUP_ADDRESS=nsqlookupd:4161
      - ENVIRONMENT=local
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=semezana
    ports:
      - "5432:5432"
    logging:
      driver: "none"

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    logging:
      driver: "none"

  nsqd:
    image: nsqio/nsq
    command:  /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    logging:
      driver: "none"
      
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
    logging:
      driver: "none"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "14268:14268"