// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Muchogoc/semezana/ent/message"
	"github.com/Muchogoc/semezana/ent/recipient"
	"github.com/Muchogoc/semezana/ent/user"
	"github.com/google/uuid"
)

// RecipientCreate is the builder for creating a Recipient entity.
type RecipientCreate struct {
	config
	mutation *RecipientMutation
	hooks    []Hook
}

// SetMessageID sets the "message_id" field.
func (rc *RecipientCreate) SetMessageID(u uuid.UUID) *RecipientCreate {
	rc.mutation.SetMessageID(u)
	return rc
}

// SetUserID sets the "user_id" field.
func (rc *RecipientCreate) SetUserID(u uuid.UUID) *RecipientCreate {
	rc.mutation.SetUserID(u)
	return rc
}

// SetStatus sets the "status" field.
func (rc *RecipientCreate) SetStatus(r recipient.Status) *RecipientCreate {
	rc.mutation.SetStatus(r)
	return rc
}

// SetDeliveredAt sets the "delivered_at" field.
func (rc *RecipientCreate) SetDeliveredAt(t time.Time) *RecipientCreate {
	rc.mutation.SetDeliveredAt(t)
	return rc
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (rc *RecipientCreate) SetNillableDeliveredAt(t *time.Time) *RecipientCreate {
	if t != nil {
		rc.SetDeliveredAt(*t)
	}
	return rc
}

// SetReadAt sets the "read_at" field.
func (rc *RecipientCreate) SetReadAt(t time.Time) *RecipientCreate {
	rc.mutation.SetReadAt(t)
	return rc
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (rc *RecipientCreate) SetNillableReadAt(t *time.Time) *RecipientCreate {
	if t != nil {
		rc.SetReadAt(*t)
	}
	return rc
}

// SetUser sets the "user" edge to the User entity.
func (rc *RecipientCreate) SetUser(u *User) *RecipientCreate {
	return rc.SetUserID(u.ID)
}

// SetMessage sets the "message" edge to the Message entity.
func (rc *RecipientCreate) SetMessage(m *Message) *RecipientCreate {
	return rc.SetMessageID(m.ID)
}

// Mutation returns the RecipientMutation object of the builder.
func (rc *RecipientCreate) Mutation() *RecipientMutation {
	return rc.mutation
}

// Save creates the Recipient in the database.
func (rc *RecipientCreate) Save(ctx context.Context) (*Recipient, error) {
	var (
		err  error
		node *Recipient
	)
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RecipientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			if node, err = rc.sqlSave(ctx); err != nil {
				return nil, err
			}
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			if rc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, rc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Recipient)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from RecipientMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RecipientCreate) SaveX(ctx context.Context) *Recipient {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RecipientCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RecipientCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RecipientCreate) check() error {
	if _, ok := rc.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "Recipient.message_id"`)}
	}
	if _, ok := rc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Recipient.user_id"`)}
	}
	if _, ok := rc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Recipient.status"`)}
	}
	if v, ok := rc.mutation.Status(); ok {
		if err := recipient.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Recipient.status": %w`, err)}
		}
	}
	if _, ok := rc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Recipient.user"`)}
	}
	if _, ok := rc.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required edge "Recipient.message"`)}
	}
	return nil
}

func (rc *RecipientCreate) sqlSave(ctx context.Context) (*Recipient, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (rc *RecipientCreate) createSpec() (*Recipient, *sqlgraph.CreateSpec) {
	var (
		_node = &Recipient{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: recipient.Table,
		}
	)
	if value, ok := rc.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: recipient.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := rc.mutation.DeliveredAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: recipient.FieldDeliveredAt,
		})
		_node.DeliveredAt = &value
	}
	if value, ok := rc.mutation.ReadAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: recipient.FieldReadAt,
		})
		_node.ReadAt = &value
	}
	if nodes := rc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recipient.UserTable,
			Columns: []string{recipient.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   recipient.MessageTable,
			Columns: []string{recipient.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: message.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecipientCreateBulk is the builder for creating many Recipient entities in bulk.
type RecipientCreateBulk struct {
	config
	builders []*RecipientCreate
}

// Save creates the Recipient entities in the database.
func (rcb *RecipientCreateBulk) Save(ctx context.Context) ([]*Recipient, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Recipient, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecipientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RecipientCreateBulk) SaveX(ctx context.Context) []*Recipient {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RecipientCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RecipientCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
